### PR TITLE
show logout section only if show_onboarding is true (first visit)

### LINKED ISSUE #267: [frontend][web] When clicking the postal code in the dashboard I'm presented with a 'logged-out' facebook button on the background
First time I opened this I though the app logged out.

### PR DESCRIPTION
**Pull request by nunofgm**
Since we only want to show logout background if it's the first user's visit (show_onboarding = true), I added validation to show that section on HTML

### CODE REVIEW

**Review by diogoteix — APPROVED** [review]

**Comment by fabioscsilva** [comment]
I believe this PR is just related with the #267. Can you remove the other issue linked?
Or if you prefer remove the click from the username?

**Comment by nunofgm** [comment]
@fabioscsilva I think that it's the same issue. I saw the video (the only description about the bug) and the only thing that is confusing the user is the logged out section because the "go back" button is no longer available.

**Comment by fabioscsilva** [comment]
@nunofgm I understood, but I confirmed with designers and that issue is to remove the click event from username

**Comment by nunofgm** [comment]
@fabioscsilva ok, I'll remove the link and fix it with the proper PR. Thanks for the clarification

**Review by fabioscsilva — APPROVED** [review]

**Pull request merged**
